"""competitor watchlist

Revision ID: 5148f37eb018
Revises: 3153839f70f1
Create Date: 2026-09-02 21:39:49.104916

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5148f37eb018'
down_revision: str | Sequence[str] | None = '3153839f70f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_watchlist',
    sa.Column('market_channel_id', sa.Uuid(), nullable=False),
    sa.Column('niche_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_channel_id'], ['market_channels.id'], name=op.f('fk_competitor_watchlist_market_channel_id_market_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_competitor_watchlist_niche_id_niches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitor_watchlist')),
    sa.UniqueConstraint('market_channel_id', name=op.f('uq_competitor_watchlist_market_channel_id'))
    )
    # market_channel_id needs no separate index: the unique constraint above
    # already creates one.
    op.create_index(op.f('ix_competitor_watchlist_niche_id'), 'competitor_watchlist', ['niche_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_watchlist_niche_id'), table_name='competitor_watchlist')
    op.drop_table('competitor_watchlist')
    # ### end Alembic commands ###
