"""research engine

Revision ID: 5ea0cddc4115
Revises: 5148f37eb018
Create Date: 2026-09-02 22:35:53.984428

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ea0cddc4115'
down_revision: str | Sequence[str] | None = '5148f37eb018'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



# Each PostgreSQL ENUM is defined once and created explicitly below:
# autogenerate would otherwise emit CREATE TYPE per table and fail on the
# second table that uses the same type.
ENUMS = {
    'ai_task_type': postgresql.ENUM('EXTRACTION', 'CLASSIFICATION', 'SCORING', 'DEDUP_ADJUDICATION', 'SEARCH', 'SYNTHESIS', name='ai_task_type', create_type=False),
    'ai_call_status': postgresql.ENUM('SUCCESS', 'ERROR', 'BLOCKED_BY_COST_LIMIT', name='ai_call_status', create_type=False),
    'pipeline_job': postgresql.ENUM('RESEARCH_POLL', 'RESEARCH_CLUSTER', 'TOPIC_SCORE', name='pipeline_job', create_type=False),
    'run_status': postgresql.ENUM('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', 'COST_LIMIT_REACHED', name='run_status', create_type=False),
    'research_provider_type': postgresql.ENUM('RSS', 'GITHUB_RELEASES', 'OFFICIAL_BLOG', 'LLM_SEARCH', 'AGGREGATOR', name='research_provider_type', create_type=False),
    'trust_level': postgresql.ENUM('OFFICIAL', 'PRIMARY', 'REPUTABLE_SECONDARY', 'AGGREGATOR', 'UNKNOWN', name='trust_level', create_type=False),
    'verification_status': postgresql.ENUM('UNVERIFIED', 'SUPPORTED', 'CONFLICTING', 'INSUFFICIENT', name='verification_status', create_type=False),
    'research_item_status': postgresql.ENUM('NEW', 'CLUSTERED', 'FILTERED', 'SELECTED', 'BACKLOG', 'VERIFIED', 'CONVERTED_TO_CONTENT', 'REJECTED', name='research_item_status', create_type=False),
    'rejection_reason': postgresql.ENUM('IRRELEVANT', 'SPAM', 'UNSAFE_TOPIC', 'CONFIRMED_JUNK', 'MANUAL_EXCLUSION', name='rejection_reason', create_type=False),
    'event_type': postgresql.ENUM('RELEASE', 'UPDATE', 'NEW_TOOL', 'RESEARCH', 'GUIDE', 'INCIDENT', 'OTHER', name='event_type', create_type=False),
    'cluster_status': postgresql.ENUM('OPEN', 'SCORED', 'SELECTED', 'BACKLOG', 'FILTERED', 'VERIFIED', 'CONTENT_CREATED', 'REJECTED', 'EXPIRED', name='cluster_status', create_type=False),
    'cluster_item_role': postgresql.ENUM('PRIMARY', 'SUPPORTING', 'DUPLICATE', name='cluster_item_role', create_type=False),
    'match_method': postgresql.ENUM('URL', 'FINGERPRINT', 'SIMHASH', 'ENTITY', 'LLM', 'SEED', name='match_method', create_type=False),
}


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for enum_type in ENUMS.values():
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generations',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('task_type', ENUMS['ai_task_type'], nullable=False),
    sa.Column('status', ENUMS['ai_call_status'], nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('batched', sa.Boolean(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=64), nullable=True),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generations'))
    )
    op.create_index('ix_ai_generations_created', 'ai_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_generations_pipeline_run_id'), 'ai_generations', ['pipeline_run_id'], unique=False)
    op.create_index('ix_ai_generations_task_created', 'ai_generations', ['task_type', 'created_at'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('job', ENUMS['pipeline_job'], nullable=False),
    sa.Column('status', ENUMS['run_status'], nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('counters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index('ix_pipeline_runs_job_created', 'pipeline_runs', ['job', 'created_at'], unique=False)
    op.create_table('research_sources',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', ENUMS['research_provider_type'], nullable=False),
    sa.Column('trust', ENUMS['trust_level'], nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_research_sources_key'))
    )
    op.create_table('research_items',
    sa.Column('research_source_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', ENUMS['research_provider_type'], nullable=False),
    sa.Column('trust', ENUMS['trust_level'], nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_excerpt', sa.Text(), nullable=True),
    sa.Column('content_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('simhash', sa.BigInteger(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('subtopic', sa.String(length=128), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('novelty_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('practical_value_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('authority_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('verification_status', ENUMS['verification_status'], nullable=False),
    sa.Column('status', ENUMS['research_item_status'], nullable=False),
    sa.Column('rejection_reason', ENUMS['rejection_reason'], nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_source_id'], ['research_sources.id'], name=op.f('fk_research_items_research_source_id_research_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_items')),
    sa.UniqueConstraint('research_source_id', 'external_id', name=op.f('uq_research_items_research_source_id_external_id'))
    )
    op.create_index(op.f('ix_research_items_research_source_id'), 'research_items', ['research_source_id'], unique=False)
    op.create_index('ix_research_items_simhash', 'research_items', ['simhash'], unique=False)
    op.create_index('ix_research_items_status_discovered', 'research_items', ['status', 'discovered_at'], unique=False)
    op.create_index('ix_research_items_url_hash', 'research_items', ['url_hash'], unique=False)
    op.create_table('research_clusters',
    sa.Column('cluster_key', sa.String(length=512), nullable=False),
    sa.Column('event_type', ENUMS['event_type'], nullable=False),
    sa.Column('canonical_title', sa.String(length=1024), nullable=False),
    sa.Column('canonical_summary', sa.Text(), nullable=True),
    sa.Column('primary_item_id', sa.Uuid(), nullable=True),
    sa.Column('vendor', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('max_trust', ENUMS['trust_level'], nullable=False),
    sa.Column('topic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_version', sa.String(length=32), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_rescore', sa.Boolean(), nullable=False),
    sa.Column('status', ENUMS['cluster_status'], nullable=False),
    sa.Column('rejection_reason', ENUMS['rejection_reason'], nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_item_id'], ['research_items.id'], name=op.f('fk_research_clusters_primary_item_id_research_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_clusters')),
    sa.UniqueConstraint('cluster_key', name=op.f('uq_research_clusters_cluster_key'))
    )
    op.create_index('ix_research_clusters_status_score', 'research_clusters', ['status', 'topic_score'], unique=False)
    op.create_table('research_cluster_items',
    sa.Column('research_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('research_item_id', sa.Uuid(), nullable=False),
    sa.Column('role', ENUMS['cluster_item_role'], nullable=False),
    sa.Column('matched_by', ENUMS['match_method'], nullable=False),
    sa.Column('similarity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_cluster_id'], ['research_clusters.id'], name=op.f('fk_research_cluster_items_research_cluster_id_research_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_item_id'], ['research_items.id'], name=op.f('fk_research_cluster_items_research_item_id_research_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_cluster_items')),
    sa.UniqueConstraint('research_cluster_id', 'research_item_id', name=op.f('uq_research_cluster_items_research_cluster_id_research_item_id'))
    )
    op.create_index(op.f('ix_research_cluster_items_research_cluster_id'), 'research_cluster_items', ['research_cluster_id'], unique=False)
    op.create_index(op.f('ix_research_cluster_items_research_item_id'), 'research_cluster_items', ['research_item_id'], unique=False)
    op.create_table('topic_scores',
    sa.Column('research_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('score_version', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('decision', ENUMS['cluster_status'], nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_cluster_id'], ['research_clusters.id'], name=op.f('fk_topic_scores_research_cluster_id_research_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_scores'))
    )
    op.create_index('ix_topic_scores_cluster_created', 'topic_scores', ['research_cluster_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_topic_scores_score_version'), 'topic_scores', ['score_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_scores_score_version'), table_name='topic_scores')
    op.drop_index('ix_topic_scores_cluster_created', table_name='topic_scores')
    op.drop_table('topic_scores')
    op.drop_index(op.f('ix_research_cluster_items_research_item_id'), table_name='research_cluster_items')
    op.drop_index(op.f('ix_research_cluster_items_research_cluster_id'), table_name='research_cluster_items')
    op.drop_table('research_cluster_items')
    op.drop_index('ix_research_clusters_status_score', table_name='research_clusters')
    op.drop_table('research_clusters')
    op.drop_index('ix_research_items_url_hash', table_name='research_items')
    op.drop_index('ix_research_items_status_discovered', table_name='research_items')
    op.drop_index('ix_research_items_simhash', table_name='research_items')
    op.drop_index(op.f('ix_research_items_research_source_id'), table_name='research_items')
    op.drop_table('research_items')
    op.drop_table('research_sources')
    op.drop_index('ix_pipeline_runs_job_created', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('ix_ai_generations_task_created', table_name='ai_generations')
    op.drop_index(op.f('ix_ai_generations_pipeline_run_id'), table_name='ai_generations')
    op.drop_index('ix_ai_generations_created', table_name='ai_generations')
    op.drop_table('ai_generations')
    # ### end Alembic commands ###

    # Autogenerate does not drop ENUM types; without this a
    # downgrade/upgrade cycle fails with "type already exists".
    bind = op.get_bind()
    for enum_type in ENUMS.values():
        enum_type.drop(bind, checkfirst=True)

