"""niche scores

Revision ID: 6f3f7edcb738
Revises: d33b2681b034
Create Date: 2026-09-02 14:00:06.094566

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f3f7edcb738'
down_revision: str | Sequence[str] | None = 'd33b2681b034'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niche_score_runs',
    sa.Column('score_version', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('niches_scored', sa.Integer(), nullable=False),
    sa.Column('niches_skipped', sa.Integer(), nullable=False),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('dataset', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niche_score_runs'))
    )
    op.create_index(op.f('ix_niche_score_runs_score_version'), 'niche_score_runs', ['score_version'], unique=False)
    op.create_table('niche_scores',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('niche_id', sa.Uuid(), nullable=False),
    sa.Column('score_version', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('channels_count', sa.Integer(), nullable=False),
    sa.Column('insufficient_data', sa.Boolean(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_niche_scores_niche_id_niches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['niche_score_runs.id'], name=op.f('fk_niche_scores_run_id_niche_score_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niche_scores'))
    )
    op.create_index(op.f('ix_niche_scores_niche_id'), 'niche_scores', ['niche_id'], unique=False)
    op.create_index(op.f('ix_niche_scores_run_id'), 'niche_scores', ['run_id'], unique=False)
    op.create_index(op.f('ix_niche_scores_score_version'), 'niche_scores', ['score_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_niche_scores_score_version'), table_name='niche_scores')
    op.drop_index(op.f('ix_niche_scores_run_id'), table_name='niche_scores')
    op.drop_index(op.f('ix_niche_scores_niche_id'), table_name='niche_scores')
    op.drop_table('niche_scores')
    op.drop_index(op.f('ix_niche_score_runs_score_version'), table_name='niche_score_runs')
    op.drop_table('niche_score_runs')
    # ### end Alembic commands ###
