"""publications

Revision ID: c39ac4cbe263
Revises: 5ea0cddc4115
Create Date: 2026-09-05 18:08:41.714923

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c39ac4cbe263'
down_revision: str | Sequence[str] | None = '5ea0cddc4115'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



# Shared enum objects created with checkfirst: 'platform' already exists,
# and autogenerate would otherwise try to create it again.
ENUMS = {
    'platform': postgresql.ENUM('TELEGRAM', 'MAX', 'UNKNOWN', name='platform', create_type=False),
    'publish_mode': postgresql.ENUM('DRY_RUN', 'LIVE', name='publish_mode', create_type=False),
    'publication_status': postgresql.ENUM('SIMULATED', 'PUBLISHED', 'FAILED', 'BLOCKED', name='publication_status', create_type=False),
}



# Shared enum objects created with checkfirst: 'platform' already exists,
# and autogenerate would otherwise try to create it again.
ENUMS = {
}


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    for enum_type in ENUMS.values():
        enum_type.create(bind, checkfirst=True)

    bind = op.get_bind()
    for enum_type in ENUMS.values():
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('platform', ENUMS['platform'], nullable=False),
    sa.Column('mode', ENUMS['publish_mode'], nullable=False),
    sa.Column('status', ENUMS['publication_status'], nullable=False),
    sa.Column('research_cluster_id', sa.Uuid(), nullable=True),
    sa.Column('channel_ref', sa.String(length=128), nullable=False),
    sa.Column('external_message_id', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_cluster_id'], ['research_clusters.id'], name=op.f('fk_publications_research_cluster_id_research_clusters'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications'))
    )
    op.create_index('ix_publications_cluster', 'publications', ['research_cluster_id'], unique=False)
    op.create_index('ix_publications_platform_created', 'publications', ['platform', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_publications_platform_created', table_name='publications')
    op.drop_index('ix_publications_cluster', table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###

    # Drop only the types this migration introduced; 'platform' is still
    # used by market_channels and niche_score_runs.
    bind = op.get_bind()
    for name in ('publish_mode', 'publication_status'):
        ENUMS[name].drop(bind, checkfirst=True)


    # Drop only the types this migration introduced; 'platform' is still
    # used by market_channels and niche_score_runs.
    bind = op.get_bind()
    for name in ('publish_mode', 'publication_status'):
        ENUMS[name].drop(bind, checkfirst=True)

