"""initial schema

Revision ID: d33b2681b034
Revises:
Create Date: 2026-09-02 13:36:31.668579

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd33b2681b034'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niches',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('raw_label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_niches')),
    sa.UniqueConstraint('slug', name=op.f('uq_niches_slug'))
    )
    op.create_table('sources',
    sa.Column('kind', sa.Enum('DIRECT_EXPORT', 'CATALOG', 'CONTENT_REFERENCE', 'OTHER', name='source_kind'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('kind', 'name', name=op.f('uq_sources_kind_name'))
    )
    op.create_table('direct_imports',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='import_status'), nullable=False),
    sa.Column('forced', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_row_count', sa.Integer(), nullable=False),
    sa.Column('rejected_row_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('channels_created', sa.Integer(), nullable=False),
    sa.Column('snapshots_created', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_direct_imports_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direct_imports'))
    )
    op.create_index(op.f('ix_direct_imports_file_checksum'), 'direct_imports', ['file_checksum'], unique=False)
    op.create_index(op.f('ix_direct_imports_source_id'), 'direct_imports', ['source_id'], unique=False)
    op.create_table('market_channels',
    sa.Column('platform', sa.Enum('TELEGRAM', 'MAX', 'UNKNOWN', name='platform'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('channel_name', sa.String(length=512), nullable=False),
    sa.Column('channel_url', sa.String(length=2048), nullable=True),
    sa.Column('niche_id', sa.Uuid(), nullable=True),
    sa.Column('first_seen_date', sa.Date(), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], name=op.f('fk_market_channels_niche_id_niches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_channels')),
    sa.UniqueConstraint('platform', 'dedupe_key', name=op.f('uq_market_channels_platform_dedupe_key'))
    )
    op.create_index(op.f('ix_market_channels_niche_id'), 'market_channels', ['niche_id'], unique=False)
    op.create_table('direct_import_rows',
    sa.Column('direct_import_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REJECTED', name='row_status'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_channel_id', sa.Uuid(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direct_import_id'], ['direct_imports.id'], name=op.f('fk_direct_import_rows_direct_import_id_direct_imports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_channel_id'], ['market_channels.id'], name=op.f('fk_direct_import_rows_market_channel_id_market_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direct_import_rows'))
    )
    op.create_index(op.f('ix_direct_import_rows_direct_import_id'), 'direct_import_rows', ['direct_import_id'], unique=False)
    op.create_index(op.f('ix_direct_import_rows_market_channel_id'), 'direct_import_rows', ['market_channel_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('market_channel_id', sa.Uuid(), nullable=False),
    sa.Column('direct_import_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('subscribers', sa.BigInteger(), nullable=True),
    sa.Column('err', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('predicted_views', sa.BigInteger(), nullable=True),
    sa.Column('cpv', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('campaign_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direct_import_id'], ['direct_imports.id'], name=op.f('fk_market_snapshots_direct_import_id_direct_imports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_channel_id'], ['market_channels.id'], name=op.f('fk_market_snapshots_market_channel_id_market_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_snapshots')),
    sa.UniqueConstraint('market_channel_id', 'direct_import_id', 'snapshot_date', name=op.f('uq_market_snapshots_market_channel_id_direct_import_id_snapshot_date'))
    )
    op.create_index(op.f('ix_market_snapshots_direct_import_id'), 'market_snapshots', ['direct_import_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_market_channel_id'), 'market_snapshots', ['market_channel_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_snapshot_date'), 'market_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_snapshots_snapshot_date'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_market_channel_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_direct_import_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_direct_import_rows_market_channel_id'), table_name='direct_import_rows')
    op.drop_index(op.f('ix_direct_import_rows_direct_import_id'), table_name='direct_import_rows')
    op.drop_table('direct_import_rows')
    op.drop_index(op.f('ix_market_channels_niche_id'), table_name='market_channels')
    op.drop_table('market_channels')
    op.drop_index(op.f('ix_direct_imports_source_id'), table_name='direct_imports')
    op.drop_index(op.f('ix_direct_imports_file_checksum'), table_name='direct_imports')
    op.drop_table('direct_imports')
    op.drop_table('sources')
    op.drop_table('niches')
    # ### end Alembic commands ###

    # Autogenerate does not drop PostgreSQL ENUM types, which would make a
    # downgrade/upgrade cycle fail with "type already exists".
    for enum_name in ('row_status', 'platform', 'import_status', 'source_kind'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
